name: todos_api
description: The interface and models for an API providing access to todos.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  equatable: ^2.0.0
  json_annotation: ^4.6.0
  meta: ^1.7.0
  uuid: ^3.0.6
  path_provider: ^2.1.5
  audioplayers: ^6.1.0
  flutter_tts: ^4.0.2
  csv: ^6.0.0
  collection: ^1.18.0
  #  gallery_saver: ^2.3.2
  permission_handler: ^11.3.0
  share_plus: ^11.0.0
  model_viewer_plus: ^1.9.3
  flutter_3d_controller: ^2.2.0
  image: ^4.5.4
  image_gallery_saver: ^2.0.3
  whiteboard: ^1.0.0
  gallery_saver: ^2.3.2

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  test: ^1.21.4


flutter:
  uses-material-design: true
  assets:
    - assets/