name: flutter_todos
description: A simple whiteboard app with save-to-gallery feature.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  whiteboard: ^1.0.0
  permission_handler: ^11.3.0
  path_provider: ^2.1.5
  image_gallery_saver: ^2.0.3
  gallery_saver: ^2.3.2
  image: ^4.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
